import { Inter } from "next/font/google"
import "./globals.css"
import Header from "../components/Header/Header"
import Footer from "../components/Footer/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Thibaut Roegiers - Développeur web",
    description: "Generated by create next app", // TODO
}

export default function RootLayout({ children }) {
    return (
        <html lang="fr" className="m-auto max-w-[1440px] p-10">
            <head></head>
            <body className={inter.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
